server:
  port: 10000

spring:
  application:
    name: ex10
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jh
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true

  jwt:
    secret: abcdefghijklmnopqrstuvwxyz01234567890

my:
  value: "welcome to my value"


