apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-config
#  namespace: maria-name
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydata;
    CREATE DATABASE IF NOT EXISTS msa;
    USE mydata;
    CREATE TABLE friends (id INT, name VARCHAR(256), age INT, gender VARCHAR(3));
    INSERT INTO friends VALUES (1, 'Abhijeet', 32, 'm');
    INSERT INTO friends VALUES (2, 'Anjali', 29, 'f');
    INSERT INTO friends VALUES (3, 'Aayush', 27, 'm');
    INSERT INTO friends VALUES (4, '길동', 28, 'm');