apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: zipkin-service-deployment
spec: # 어떻게 만들지 대한 내용
  replicas: 1 # 몇개의 pod 만들래?
  selector:
    matchLabels:
      app: zipkin-service # 쿠버네티스 안에서 변수명
  template:
    metadata:
      labels:
        app: zipkin-service # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: zipkin-service
          image: openzipkin/zipkin # dockerhub 에 있는 image
#          imagePullPolicy: Always # 매번 이미지를 가져오도록 설정
          ports:
            - containerPort: 9411 #default one

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: zipkin-service