# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.0.40:9090"]
  - job_name: "intel-20000"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "192.168.0.40:20000" ]
  - job_name: "first-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "192.168.0.40:40001" ]
  - job_name: "second-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "192.168.0.40:40002" ]
  - job_name: "user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "192.168.0.40:40003" ]
