server:
  port: 8000

# ??? ??? ?? ?????
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**

# localhost:8000/first-service/test
# ->
# FIRST-SERVICE/first-servuce/test