apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-config-user
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS msa CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    use msa;
    drop table if exists users;
    create table users
    (
        id       bigint       not null auto_increment,
        email    varchar(50)  not null,
        name     varchar(50)  not null,
        password varchar(100) not null,
        thumb    varchar(255),
        user_id  varchar(255) not null,
        primary key (id)
    ) engine=InnoDB;
    alter table if exists users add constraint user_email_unique unique (email);
    alter table if exists users add constraint user_userid_unique unique (user_id);