server:
  port: 20001

spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  output:
    ansi:
      enabled: always

  # zipkin:
  #   base-url: http://localhost:9411
  #   enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: false
    show-sql: true
    open-in-view: false

#logging:
#  level:
#    com.green.userservice.feignclient: DEBUG
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

# management:
#   tracing:
#     sampling:
#       probability: 1.0
#     propagation:
#       consume: B3
#       produce: B3
#   zipkin:
#     tracing:
#       endpoint: http://localhost:9411/api/v2/spans

management:
  endpoints:
    web:
      exposure:
        include: "*"

first-service-url: http://localhost:40001
catalog-service-url: http://localhost:20002