apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-k8s-configmap
data:
  gateway_ip: "172.30.1.58"
  token_expiration_time: "86400000"
  token_secret: "APPLE_YOUR_SECRETKEY_20240522_FOR_SPRING_CLOUD_LOGIN_#1"

  order-service-url: "http://order-service:10000"
  bootstrap-servers: "172.30.1.58:9092"

  first-service-port: "40001"
  second-service-port: "40002"
  user-service-port: "40003"
  order-service-port: "40004"
  catalog-service-port: "40005"

  spring-datasource-url: "jdbc:mariadb://mariadb:3306/msa"
  spring-datasource-username: "root"