apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-k8s-configmap
data:
  gateway_ip: "172.30.1.58"
  token_expiration_time: "86400000"
  token_secret: "APPLE_YOUR_SECRETKEY_20240522_FOR_SPRING_CLOUD_LOGIN_#1"

  user-service-url: "http://user-service:40003"
  order-service-url: "http://order-service:40004"
  catalog-service-url: "http://catalog-service:40005"

  first-service-port: "40001"
  second-service-port: "40002"
  user-service-port: "40003"
  order-service-port: "40004"
  catalog-service-port: "40005"

  spring-datasource-url-user: "jdbc:mariadb://mariadb-user:3306/msa"
  spring-datasource-url-order: "jdbc:mariadb://mariadb-order:3306/msa"
  spring-datasource-url-catalog: "jdbc:mariadb://mariadb-catalog:3306/msa"
  spring-datasource-username: "root"

  management-zipkin-tracing-endpoint: "http://zipkin-service:9411/api/v2/spans"

  spring-kafka-bootstrap-servers: "192.168.65.3:9094"